insert into review (owner_id, car_id, comment, rating) values (1, 1, 'User-centric transitional task-force', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 2, 'Multi-channelled actuating Graphical User Interface', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 3, 'Profound asymmetric capacity', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 4, 'Organic background migration', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 5, 'Synergized content-based algorithm', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 6, 'Organized empowering functionalities', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 7, 'Focused dedicated secured line', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 8, 'Pre-emptive holistic moratorium', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 9, 'Multi-layered multi-state standardization', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 11, 'Organic even-keeled architecture', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 12, 'Pre-emptive full-range encryption', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 13, 'Optional interactive structure', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 14, 'Team-oriented dedicated contingency', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 15, 'Grass-roots local frame', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 16, 'Digitized asymmetric software', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 17, 'Public-key discrete moratorium', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 18, 'Open-architected grid-enabled strategy', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 19, 'Persevering explicit capability', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 21, 'Configurable next generation application', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 22, 'Triple-buffered exuding complexity', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 23, 'Secured demand-driven local area network', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 24, 'Enhanced neutral access', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 25, 'Re-engineered incremental encryption', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 26, 'Intuitive bandwidth-monitored definition', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 27, 'Balanced bandwidth-monitored access', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 28, 'Optional foreground definition', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 29, 'Re-engineered zero administration paradigm', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 31, 'Streamlined neutral frame', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 32, 'Compatible client-server task-force', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 33, 'Realigned systemic project', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 34, 'Intuitive heuristic capability', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 35, 'Up-sized directional paradigm', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 36, 'Vision-oriented fresh-thinking function', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 37, 'Self-enabling transitional archive', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 38, 'Virtual intangible local area network', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 39, 'Reactive zero tolerance support', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 41, 'Front-line holistic complexity', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 42, 'Up-sized bifurcated task-force', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 43, 'Robust object-oriented moderator', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 44, 'Function-based local portal', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 45, 'Pre-emptive high-level matrices', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 46, 'Integrated stable local area network', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 47, 'Robust multi-tasking initiative', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 48, 'Universal intangible analyzer', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 49, 'Face to face disintermediate open architecture', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 51, 'Progressive upward-trending adapter', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 52, 'Automated leading edge database', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 53, 'Phased object-oriented local area network', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 54, 'Cloned even-keeled application', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 55, 'Versatile local workforce', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 56, 'Cross-group reciprocal synergy', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 57, 'Switchable reciprocal internet solution', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 58, 'Customizable intangible conglomeration', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 59, 'Grass-roots motivating local area network', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 61, 'Future-proofed even-keeled capacity', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 62, 'Team-oriented tangible artificial intelligence', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 63, 'Organized scalable adapter', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 64, 'Multi-lateral optimal architecture', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 65, 'Synergistic coherent concept', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 66, 'Team-oriented static ability', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 67, 'Phased well-modulated info-mediaries', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 68, 'Open-source grid-enabled extranet', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 69, 'Down-sized leading edge firmware', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 71, 'Cross-platform explicit policy', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 72, 'Digitized analyzing success', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 73, 'Digitized content-based service-desk', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 74, 'Advanced maximized architecture', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 75, 'Persistent logistical infrastructure', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 76, 'Visionary content-based artificial intelligence', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 77, 'Advanced radical firmware', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 78, 'Persevering empowering internet solution', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 79, 'Implemented multi-tasking conglomeration', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 81, 'Expanded needs-based matrices', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 82, 'Secured 5th generation superstructure', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 83, 'Phased eco-centric portal', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 84, 'Up-sized contextually-based budgetary management', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 85, 'Digitized zero defect hub', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 86, 'Polarised user-facing product', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 87, 'Fully-configurable exuding installation', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 88, 'Vision-oriented optimizing orchestration', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 89, 'Adaptive methodical analyzer', 4);
insert into review (owner_id, car_id, comment, rating) values (1, 91, 'Enhanced 6th generation leverage', 1);
insert into review (owner_id, car_id, comment, rating) values (2, 92, 'Assimilated non-volatile superstructure', 2);
insert into review (owner_id, car_id, comment, rating) values (3, 93, 'De-engineered non-volatile service-desk', 3);
insert into review (owner_id, car_id, comment, rating) values (4, 94, 'Team-oriented global paradigm', 4);
insert into review (owner_id, car_id, comment, rating) values (5, 95, 'Re-engineered cohesive leverage', 0);
insert into review (owner_id, car_id, comment, rating) values (6, 96, 'Enterprise-wide zero administration algorithm', 1);
insert into review (owner_id, car_id, comment, rating) values (7, 97, 'Operative client-server Graphic Interface', 2);
insert into review (owner_id, car_id, comment, rating) values (8, 98, 'Extended fresh-thinking attitude', 3);
insert into review (owner_id, car_id, comment, rating) values (9, 99, 'Expanded dedicated intranet', 4);
